name: Test flask
on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: instll ngrok
      run:  curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
    - name: Start Ngrok
      run: |
        ngrok config add-authtoken 2RhU6sRGtMKKVtslhO5e0MKijcS_4ekpa6k3CKog6XCSCfmUH
    - name: run Ngrok
      run: |
        ngrok http 5000 &
    - name: ip
      shell: python
      run: |
        import socket 
        hostname = socket.gethostname()
        local_ip = socket.gethostbyname(hostname)
        print(local_ip)
    - name: Run Tests
      run: python main.py

    - name: Wait 28 minutes
      run: sleep 1680  # 28 minutes = 28 * 60 seconds

    - name: Stop main.py
      run: pkill -f "python main.py"

    - name: Finalize
      run: |
        ngrok killall
    
